language: python

python:
    - "2.6"
    - "2.7"

env:
    - DJANGO=1.4.10
    - DJANGO=1.5.5

virtualenv:
    system_site_packages: true

install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt
    - pip install flake8

before_script:
    flake8

services:
    - memcache

script:
    - coverage run test_suite.py

after_success:
    - coveralls
